# Generated by Django 4.2.7 on 2025-02-27 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movie_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='certificate',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
